"""Test case definitions for zsh-aisuggestions LLM evaluation.

80 test cases across 5 categories:
  - rewrite_simple:  20 cases — simple natural language to shell command
  - rewrite_complex: 20 cases — multi-pipe / complex translations
  - rewrite_context: 10 cases — context-aware / error recovery
  - complete_end:    15 cases — end-of-line completion
  - complete_mid:    15 cases — mid-command completion

Each required_fragments entry is either:
  - str:   the fragment must appear in the suggestion (case-insensitive)
  - tuple: at least ONE of the fragments must appear (case-insensitive)
"""

# Default context used for most cases
DEFAULT_CONTEXT = {
    "cwd": "/Users/user/projects",
    "git_branch": "",
    "git_dirty": False,
    "last_exit_code": 0,
    "last_command": "",
    "shell": "zsh",
    "os": "macos",
    "recent_history": [],
}

# ─────────────────────────────────────────────────────────────────────────────
# Category 1: Rewrite — Simple NL Translation (20 cases)
# ─────────────────────────────────────────────────────────────────────────────

REWRITE_SIMPLE = [
    {
        "id": 1,
        "category": "rewrite_simple",
        "description": "list large files in home directory",
        "trigger_mode": "rewrite",
        "buffer": "list all files larger than 100MB in home directory",
        "cursor_position": 49,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["find", "100"],
        "forbidden_fragments": ["<file>", "<path>"],
    },
    {
        "id": 2,
        "category": "rewrite_simple",
        "description": "disk usage sorted by size",
        "trigger_mode": "rewrite",
        "buffer": "show disk usage sorted by size",
        "cursor_position": 30,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["du", "sort"],
    },
    {
        "id": 3,
        "category": "rewrite_simple",
        "description": "count lines in python files",
        "trigger_mode": "rewrite",
        "buffer": "count number of lines in all python files",
        "cursor_position": 41,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("wc", "find"), ".py"],
    },
    {
        "id": 4,
        "category": "rewrite_simple",
        "description": "find processes on port 8080",
        "trigger_mode": "rewrite",
        "buffer": "find all processes using port 8080",
        "cursor_position": 33,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("lsof", "ss", "netstat", "fuser"), "8080"],
    },
    {
        "id": 5,
        "category": "rewrite_simple",
        "description": "git log last 5 one-line",
        "trigger_mode": "rewrite",
        "buffer": "show git log for the last 5 commits one line each",
        "cursor_position": 49,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["git log", "5"],
    },
    {
        "id": 6,
        "category": "rewrite_simple",
        "description": "compress src to tar.gz",
        "trigger_mode": "rewrite",
        "buffer": "compress the src folder into a tar.gz file",
        "cursor_position": 43,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["tar", "src"],
    },
    {
        "id": 7,
        "category": "rewrite_simple",
        "description": "download a URL",
        "trigger_mode": "rewrite",
        "buffer": "download the file at https://example.com/data.csv",
        "cursor_position": 49,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("curl", "wget"), "https://example.com/data.csv"],
    },
    {
        "id": 8,
        "category": "rewrite_simple",
        "description": "env vars containing PATH",
        "trigger_mode": "rewrite",
        "buffer": "show all environment variables containing PATH",
        "cursor_position": 46,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("env", "printenv", "export", "set"), "grep", "PATH"],
    },
    {
        "id": 9,
        "category": "rewrite_simple",
        "description": "kill all python processes",
        "trigger_mode": "rewrite",
        "buffer": "kill all python processes",
        "cursor_position": 24,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("kill", "pkill", "killall"), "python"],
    },
    {
        "id": 10,
        "category": "rewrite_simple",
        "description": "mkdir and cd into it",
        "trigger_mode": "rewrite",
        "buffer": "create a new directory called myproject and enter it",
        "cursor_position": 51,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["mkdir", "myproject", "cd"],
    },
    {
        "id": 11,
        "category": "rewrite_simple",
        "description": "show memory usage",
        "trigger_mode": "rewrite",
        "buffer": "show current memory usage",
        "cursor_position": 25,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("free", "top", "vm_stat", "htop", "memory_pressure", "ps", "sysctl")],
    },
    {
        "id": 12,
        "category": "rewrite_simple",
        "description": "list all docker containers",
        "trigger_mode": "rewrite",
        "buffer": "list all docker containers including stopped ones",
        "cursor_position": 49,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["docker", ("ps", "container"), "-a"],
    },
    {
        "id": 13,
        "category": "rewrite_simple",
        "description": "check port 443 on google",
        "trigger_mode": "rewrite",
        "buffer": "check if port 443 is open on google.com",
        "cursor_position": 38,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("nc", "nmap", "curl", "openssl", "ncat"), "443", "google.com"],
    },
    {
        "id": 14,
        "category": "rewrite_simple",
        "description": "tail syslog 20 lines",
        "trigger_mode": "rewrite",
        "buffer": "show the last 20 lines of syslog",
        "cursor_position": 32,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["tail", "20", ("syslog", "/var/log", "system.log", "log show")],
    },
    {
        "id": 15,
        "category": "rewrite_simple",
        "description": "chmod 755 all directories",
        "trigger_mode": "rewrite",
        "buffer": "recursively change permissions to 755 for all directories in current path",
        "cursor_position": 72,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("find", "chmod"), "755", ("-type d", "directory")],
    },
    {
        "id": 16,
        "category": "rewrite_simple",
        "description": "show public IP",
        "trigger_mode": "rewrite",
        "buffer": "display my public IP address",
        "cursor_position": 28,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("curl", "wget", "dig")],
    },
    {
        "id": 17,
        "category": "rewrite_simple",
        "description": "list listening TCP ports",
        "trigger_mode": "rewrite",
        "buffer": "list all listening TCP ports",
        "cursor_position": 28,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("ss", "netstat", "lsof")],
    },
    {
        "id": 18,
        "category": "rewrite_simple",
        "description": "subdirectory sizes",
        "trigger_mode": "rewrite",
        "buffer": "show the size of each subdirectory in current folder",
        "cursor_position": 52,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["du"],
    },
    {
        "id": 19,
        "category": "rewrite_simple",
        "description": "create python venv",
        "trigger_mode": "rewrite",
        "buffer": "create a python virtual environment called venv",
        "cursor_position": 47,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("python", "python3"), ("venv", "virtualenv")],
    },
    {
        "id": 20,
        "category": "rewrite_simple",
        "description": "watch ls every 2 seconds",
        "trigger_mode": "rewrite",
        "buffer": "watch the output of ls every 2 seconds",
        "cursor_position": 38,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["watch", "ls"],
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Category 2: Rewrite — Complex Multi-pipe (20 cases)
# ─────────────────────────────────────────────────────────────────────────────

REWRITE_COMPLEX = [
    {
        "id": 21,
        "category": "rewrite_complex",
        "description": "get PIDs of a process",
        "trigger_mode": "rewrite",
        "buffer": "ps aux to get all proc ids of opencode",
        "cursor_position": 38,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("ps", "pgrep"), "opencode", ("awk", "$2", "pgrep", "pid")],
    },
    {
        "id": 22,
        "category": "rewrite_complex",
        "description": "find and delete old log files",
        "trigger_mode": "rewrite",
        "buffer": "find all .log files modified in the last 24 hours and delete them",
        "cursor_position": 64,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["find", ".log", ("-mtime", "-mmin"), ("-delete", "rm", "xargs")],
    },
    {
        "id": 23,
        "category": "rewrite_complex",
        "description": "top 10 largest files recursive",
        "trigger_mode": "rewrite",
        "buffer": "list top 10 largest files in current directory recursively",
        "cursor_position": 57,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("find", "du"), "sort", ("head", "10")],
    },
    {
        "id": 24,
        "category": "rewrite_complex",
        "description": "count unique IPs in log",
        "trigger_mode": "rewrite",
        "buffer": "count unique IP addresses in access.log",
        "cursor_position": 38,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("awk", "cut", "grep"), ("sort", "uniq"), ("wc", "count", "uniq")],
    },
    {
        "id": 25,
        "category": "rewrite_complex",
        "description": "replace tabs with spaces in .py",
        "trigger_mode": "rewrite",
        "buffer": "replace all tabs with 4 spaces in every .py file",
        "cursor_position": 48,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("sed", "find", "perl", "expand"), ".py"],
    },
    {
        "id": 26,
        "category": "rewrite_complex",
        "description": "5 most recently modified files",
        "trigger_mode": "rewrite",
        "buffer": "show the 5 most recently modified files in current directory",
        "cursor_position": 59,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("ls", "find"), ("5", "head")],
    },
    {
        "id": 27,
        "category": "rewrite_complex",
        "description": "total size of jpg files",
        "trigger_mode": "rewrite",
        "buffer": "get the total size of all .jpg files in Downloads",
        "cursor_position": 49,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("find", "du", "ls"), (".jpg", "jpg"), ("Downloads", "downloads")],
    },
    {
        "id": 28,
        "category": "rewrite_complex",
        "description": "extract emails from file",
        "trigger_mode": "rewrite",
        "buffer": "extract all email addresses from input.txt",
        "cursor_position": 42,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("grep", "awk", "sed", "perl"), "input.txt"],
    },
    {
        "id": 29,
        "category": "rewrite_complex",
        "description": "tail -f with error highlight",
        "trigger_mode": "rewrite",
        "buffer": "monitor a log file in real time and highlight ERROR lines",
        "cursor_position": 56,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("tail", "less"), ("grep", "color", "awk", "sed"), ("ERROR", "error")],
    },
    {
        "id": 30,
        "category": "rewrite_complex",
        "description": "grep TODO in src directory",
        "trigger_mode": "rewrite",
        "buffer": "find all files containing TODO in the src directory",
        "cursor_position": 50,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("grep", "rg", "ag", "ack"), "TODO", "src"],
    },
    {
        "id": 31,
        "category": "rewrite_complex",
        "description": "top 5 procs by memory",
        "trigger_mode": "rewrite",
        "buffer": "show top 5 processes by memory usage",
        "cursor_position": 35,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("ps", "top"), ("sort", "--sort", "mem", "rss", "%mem")],
    },
    {
        "id": 32,
        "category": "rewrite_complex",
        "description": "git branches by commit date",
        "trigger_mode": "rewrite",
        "buffer": "list all git branches sorted by last commit date",
        "cursor_position": 48,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["git", ("branch", "for-each-ref"), ("sort", "committerdate", "date")],
    },
    {
        "id": 33,
        "category": "rewrite_complex",
        "description": "remove all node_modules recursively",
        "trigger_mode": "rewrite",
        "buffer": "find and remove all node_modules directories recursively",
        "cursor_position": 55,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["find", "node_modules", ("-exec", "xargs", "-delete", "rm")],
    },
    {
        "id": 34,
        "category": "rewrite_complex",
        "description": "concatenate all csv files",
        "trigger_mode": "rewrite",
        "buffer": "concatenate all csv files in current directory into one",
        "cursor_position": 54,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["cat", (".csv", "csv")],
    },
    {
        "id": 35,
        "category": "rewrite_complex",
        "description": "diff side by side",
        "trigger_mode": "rewrite",
        "buffer": "show differences between two files side by side",
        "cursor_position": 47,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("diff", "sdiff", "vimdiff", "colordiff")],
    },
    {
        "id": 36,
        "category": "rewrite_complex",
        "description": "count files per subdirectory",
        "trigger_mode": "rewrite",
        "buffer": "count the number of files in each subdirectory",
        "cursor_position": 46,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("find", "ls", "for"), ("wc", "count")],
    },
    {
        "id": 37,
        "category": "rewrite_complex",
        "description": "rename .jpeg to .jpg",
        "trigger_mode": "rewrite",
        "buffer": "rename all .jpeg files to .jpg in current directory",
        "cursor_position": 50,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("rename", "mv", "for", "zmv"), ".jpeg", ".jpg"],
    },
    {
        "id": 38,
        "category": "rewrite_complex",
        "description": "failed SSH logins in auth.log",
        "trigger_mode": "rewrite",
        "buffer": "show all failed SSH login attempts from auth.log",
        "cursor_position": 48,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("grep", "awk", "cat", "log show"), ("auth.log", "secure", "log show"), ("Failed", "fail", "invalid", "Fail", "Failed password")],
    },
    {
        "id": 39,
        "category": "rewrite_complex",
        "description": "find broken symlinks",
        "trigger_mode": "rewrite",
        "buffer": "find all symlinks that are broken in current directory",
        "cursor_position": 53,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["find", ("-type l", "symlink", "-xtype", "-L")],
    },
    {
        "id": 40,
        "category": "rewrite_complex",
        "description": "tree view 2 levels deep",
        "trigger_mode": "rewrite",
        "buffer": "show a tree view of current directory 2 levels deep",
        "cursor_position": 51,
        "context": DEFAULT_CONTEXT,
        "required_fragments": [("tree", "find"), "2"],
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Category 3: Rewrite — Context-aware / Error Recovery (10 cases)
# ─────────────────────────────────────────────────────────────────────────────

REWRITE_CONTEXT = [
    {
        "id": 41,
        "category": "rewrite_context",
        "description": "npm start after failed install",
        "trigger_mode": "rewrite",
        "buffer": "npm start",
        "cursor_position": 9,
        "context": {**DEFAULT_CONTEXT, "last_command": "npm install", "last_exit_code": 1,
                    "recent_history": ["npm install"]},
        "required_fragments": [("npm install", "npm ci", "npm start", "npm run")],
    },
    {
        "id": 42,
        "category": "rewrite_context",
        "description": "python not found (127)",
        "trigger_mode": "rewrite",
        "buffer": "python app.py",
        "cursor_position": 13,
        "context": {**DEFAULT_CONTEXT, "last_command": "python app.py", "last_exit_code": 127,
                    "recent_history": ["python app.py"]},
        "required_fragments": [("python3", "pip install", "which python", "pyenv")],
    },
    {
        "id": 43,
        "category": "rewrite_context",
        "description": "git push rejected",
        "trigger_mode": "rewrite",
        "buffer": "git push",
        "cursor_position": 8,
        "context": {**DEFAULT_CONTEXT, "last_command": "git push", "last_exit_code": 128,
                    "git_branch": "feature-x", "recent_history": ["git push"]},
        "required_fragments": [("git pull", "--force", "--set-upstream", "-u", "git push")],
    },
    {
        "id": 44,
        "category": "rewrite_context",
        "description": "make build failed",
        "trigger_mode": "rewrite",
        "buffer": "make build",
        "cursor_position": 10,
        "context": {**DEFAULT_CONTEXT, "last_command": "make build", "last_exit_code": 2,
                    "recent_history": ["make build"]},
        "required_fragments": [("make", "cmake", "clean", "build")],
    },
    {
        "id": 45,
        "category": "rewrite_context",
        "description": "docker-compose not found",
        "trigger_mode": "rewrite",
        "buffer": "docker compose up",
        "cursor_position": 17,
        "context": {**DEFAULT_CONTEXT, "last_command": "docker-compose up", "last_exit_code": 127,
                    "recent_history": ["docker-compose up"]},
        "required_fragments": [("docker compose", "docker-compose", "docker")],
    },
    {
        "id": 46,
        "category": "rewrite_context",
        "description": "ssh connection refused",
        "trigger_mode": "rewrite",
        "buffer": "ssh server",
        "cursor_position": 10,
        "context": {**DEFAULT_CONTEXT, "last_command": "ssh server", "last_exit_code": 255,
                    "recent_history": ["ssh server"]},
        "required_fragments": ["ssh"],
    },
    {
        "id": 47,
        "category": "rewrite_context",
        "description": "curl connection refused",
        "trigger_mode": "rewrite",
        "buffer": "curl localhost:3000",
        "cursor_position": 19,
        "context": {**DEFAULT_CONTEXT, "last_command": "curl localhost:3000", "last_exit_code": 7,
                    "recent_history": ["curl localhost:3000"]},
        "required_fragments": ["curl", ("3000", "localhost")],
    },
    {
        "id": 48,
        "category": "rewrite_context",
        "description": "pip install permission denied",
        "trigger_mode": "rewrite",
        "buffer": "pip install pandas",
        "cursor_position": 18,
        "context": {**DEFAULT_CONTEXT, "last_command": "pip install pandas", "last_exit_code": 1,
                    "recent_history": ["pip install pandas"]},
        "required_fragments": [("pip3", "pip", "python -m pip", "python3 -m pip")],
    },
    {
        "id": 49,
        "category": "rewrite_context",
        "description": "ls nonexistent dir",
        "trigger_mode": "rewrite",
        "buffer": "ls /nonexistent",
        "cursor_position": 15,
        "context": {**DEFAULT_CONTEXT, "last_command": "ls /nonexistent", "last_exit_code": 2,
                    "recent_history": ["ls /nonexistent"]},
        "required_fragments": ["ls"],
    },
    {
        "id": 50,
        "category": "rewrite_context",
        "description": "cargo build failed",
        "trigger_mode": "rewrite",
        "buffer": "cargo build",
        "cursor_position": 11,
        "context": {**DEFAULT_CONTEXT, "last_command": "cargo build", "last_exit_code": 101,
                    "recent_history": ["cargo build"]},
        "required_fragments": ["cargo"],
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Category 4: Complete — End-of-line (15 cases)
# ─────────────────────────────────────────────────────────────────────────────

COMPLETE_END = [
    {
        "id": 51,
        "category": "complete_end",
        "description": "docker run -it completion",
        "trigger_mode": "complete",
        "buffer": "docker run -it",
        "cursor_position": 14,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["docker run -it"],
    },
    {
        "id": 52,
        "category": "complete_end",
        "description": "git commit -m completion",
        "trigger_mode": "complete",
        "buffer": "git commit -m",
        "cursor_position": 13,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["git commit -m", '"'],
    },
    {
        "id": 53,
        "category": "complete_end",
        "description": "kubectl get pods completion",
        "trigger_mode": "complete",
        "buffer": "kubectl get pods -",
        "cursor_position": 18,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["kubectl get pods -"],
    },
    {
        "id": 54,
        "category": "complete_end",
        "description": "ssh -i completion",
        "trigger_mode": "complete",
        "buffer": "ssh -i",
        "cursor_position": 6,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["ssh -i"],
    },
    {
        "id": 55,
        "category": "complete_end",
        "description": "find delete completion",
        "trigger_mode": "complete",
        "buffer": 'find . -name "*.log" -',
        "cursor_position": 22,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ['find . -name "*.log" -'],
    },
    {
        "id": 56,
        "category": "complete_end",
        "description": "tar -xzf completion",
        "trigger_mode": "complete",
        "buffer": "tar -xzf a",
        "cursor_position": 10,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["tar -xzf a"],
    },
    {
        "id": 57,
        "category": "complete_end",
        "description": 'grep -rn TODO completion',
        "trigger_mode": "complete",
        "buffer": 'grep -rn "TODO"',
        "cursor_position": 15,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ['grep -rn "TODO"'],
    },
    {
        "id": 58,
        "category": "complete_end",
        "description": "rsync -avz completion",
        "trigger_mode": "complete",
        "buffer": "rsync -avz",
        "cursor_position": 10,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["rsync -avz"],
    },
    {
        "id": 59,
        "category": "complete_end",
        "description": "chmod 755 completion",
        "trigger_mode": "complete",
        "buffer": "chmod 755",
        "cursor_position": 9,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["chmod 755"],
    },
    {
        "id": 60,
        "category": "complete_end",
        "description": "curl -X POST -H completion",
        "trigger_mode": "complete",
        "buffer": "curl -X POST -H",
        "cursor_position": 15,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["curl -X POST -H"],
    },
    {
        "id": 61,
        "category": "complete_end",
        "description": "python3 -m pytest completion",
        "trigger_mode": "complete",
        "buffer": "python3 -m pytest ",
        "cursor_position": 18,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["python3 -m pytest "],
    },
    {
        "id": 62,
        "category": "complete_end",
        "description": "git log --oneline completion",
        "trigger_mode": "complete",
        "buffer": "git log --oneline -",
        "cursor_position": 19,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["git log --oneline -"],
    },
    {
        "id": 63,
        "category": "complete_end",
        "description": "npm install --save-dev completion",
        "trigger_mode": "complete",
        "buffer": "npm install --save-dev ",
        "cursor_position": 23,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["npm install --save-dev "],
    },
    {
        "id": 64,
        "category": "complete_end",
        "description": "scp remote path completion",
        "trigger_mode": "complete",
        "buffer": "scp user@remote:",
        "cursor_position": 16,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["scp user@remote:"],
    },
    {
        "id": 65,
        "category": "complete_end",
        "description": "awk print completion",
        "trigger_mode": "complete",
        "buffer": "awk '{print $1}' a",
        "cursor_position": 18,
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["awk '{print $1}'"],
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Category 5: Complete — Mid-command (15 cases)
# ─────────────────────────────────────────────────────────────────────────────

COMPLETE_MID = [
    {
        "id": 66,
        "category": "complete_mid",
        "description": "find -exec completion",
        "trigger_mode": "complete",
        "buffer": 'find . -name "*.py" -exec {} +',
        "cursor_position": 25,  # right after "-exec "... cursor after "-exec"
        "context": DEFAULT_CONTEXT,
        # LLM should insert a command like "grep TODO" between -exec and {} +
        "required_fragments": [("grep", "rm", "chmod", "cat", "sed", "xargs", "python3", "python", "wc")],
    },
    {
        "id": 67,
        "category": "complete_mid",
        "description": "docker --name completion",
        "trigger_mode": "complete",
        "buffer": "docker run --rm --name -p 8080:80 nginx",
        "cursor_position": 23,  # right after "--name "... cursor after "--name"
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["docker run", "nginx"],
    },
    {
        "id": 68,
        "category": "complete_mid",
        "description": "awk -F delimiter completion",
        "trigger_mode": "complete",
        "buffer": "awk -F '{print $1, $3}' data.csv",
        "cursor_position": 6,  # right after "-F"
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["awk -F", "data.csv"],
    },
    {
        "id": 69,
        "category": "complete_mid",
        "description": "sed replacement completion",
        "trigger_mode": "complete",
        "buffer": "sed -i 's/old//g' file.txt",
        "cursor_position": 14,  # right after "s/old/"
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["sed", "file.txt"],
    },
    {
        "id": 70,
        "category": "complete_mid",
        "description": "ssh -L port forward completion",
        "trigger_mode": "complete",
        "buffer": "ssh -L 8080: user@server",
        "cursor_position": 12,  # right after "8080:"
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["ssh -L 8080:", "user@server"],
    },
    {
        "id": 71,
        "category": "complete_mid",
        "description": "git log --author completion",
        "trigger_mode": "complete",
        "buffer": 'git log --since="2024-01-01" --author=',
        "cursor_position": 38,  # right after "--author="
        "context": DEFAULT_CONTEXT,
        "required_fragments": ['git log --since="2024-01-01" --author='],
    },
    {
        "id": 72,
        "category": "complete_mid",
        "description": "env PYTHONPATH= completion",
        "trigger_mode": "complete",
        "buffer": "env PYTHONPATH= python3 script.py",
        "cursor_position": 15,  # right after "PYTHONPATH="
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["env PYTHONPATH=", "python3 script.py"],
    },
    {
        "id": 73,
        "category": "complete_mid",
        "description": "tar --exclude completion",
        "trigger_mode": "complete",
        "buffer": "tar -czf backup.tar.gz --exclude= src/",
        "cursor_position": 33,  # right after "--exclude="
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["tar", "--exclude=", "src/"],
    },
    {
        "id": 74,
        "category": "complete_mid",
        "description": "grep --include completion",
        "trigger_mode": "complete",
        "buffer": 'grep -r "pattern" --include= src/',
        "cursor_position": 28,  # right after "--include="
        "context": DEFAULT_CONTEXT,
        "required_fragments": ['grep -r "pattern" --include=', "src/"],
    },
    {
        "id": 75,
        "category": "complete_mid",
        "description": "git diff -- path completion",
        "trigger_mode": "complete",
        "buffer": "git diff HEAD~3..HEAD -- src/",
        "cursor_position": 24,  # right after "-- "
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["git diff HEAD~3..HEAD --"],
    },
    {
        "id": 76,
        "category": "complete_mid",
        "description": "curl Authorization header completion",
        "trigger_mode": "complete",
        "buffer": 'curl -H "Authorization: " https://api.example.com',
        "cursor_position": 24,  # right after "Authorization: "
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["curl", "Authorization:", "https://api.example.com"],
    },
    {
        "id": 77,
        "category": "complete_mid",
        "description": "find -mtime completion",
        "trigger_mode": "complete",
        "buffer": 'find /var/log -name "*.log" -mtime  -delete',
        "cursor_position": 35,  # right after "-mtime "
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["find /var/log", "-mtime", "-delete"],
    },
    {
        "id": 78,
        "category": "complete_mid",
        "description": "docker build -t tag completion",
        "trigger_mode": "complete",
        "buffer": "docker build -t myapp: .",
        "cursor_position": 22,  # right after "myapp:"
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["docker build -t myapp:", "."],
    },
    {
        "id": 79,
        "category": "complete_mid",
        "description": "git remote add origin URL completion",
        "trigger_mode": "complete",
        "buffer": "git remote add origin ",
        "cursor_position": 22,  # right after "origin "
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["git remote add origin"],
    },
    {
        "id": 80,
        "category": "complete_mid",
        "description": "python3 -c inline code completion",
        "trigger_mode": "complete",
        "buffer": 'python3 -c "import sys; print()"',
        "cursor_position": 30,  # right after "print("
        "context": DEFAULT_CONTEXT,
        "required_fragments": ["python3 -c", "import sys;", "print("],
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# All cases combined
# ─────────────────────────────────────────────────────────────────────────────

ALL_CASES = REWRITE_SIMPLE + REWRITE_COMPLEX + REWRITE_CONTEXT + COMPLETE_END + COMPLETE_MID

CATEGORIES = {
    "rewrite_simple": REWRITE_SIMPLE,
    "rewrite_complex": REWRITE_COMPLEX,
    "rewrite_context": REWRITE_CONTEXT,
    "complete_end": COMPLETE_END,
    "complete_mid": COMPLETE_MID,
}

CATEGORY_LABELS = {
    "rewrite_simple": "Rewrite Simple",
    "rewrite_complex": "Rewrite Complex",
    "rewrite_context": "Rewrite Context",
    "complete_end": "Complete End",
    "complete_mid": "Complete Mid",
}
